data:
  dirs:
    base: "data"
    raw: "raw"
    processed: "processed"
  files:
    raw_data: "WA_Fn-UseC_-Telco-Customer-Churn.csv"
    processed_data: "telco_customer_churn_processed.parquet"
    processed_csv: "telco_customer_churn_processed.csv"
